language: node_js
node_js:
  - 16

services:
  - docker

# Pre-testing installs
install:
  - echo "project has nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests. Yes there will be tests"

script:
  - docker --version # print the version for logging here.
  - docker build -t udagram-reverseproxy ./udagram-reverse-proxy
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker built -t udagram-api-user ./udagram-api-user
  - docker built -t udagram-frontend ./udagram-frontend
  # Tagging
  - docker tag udagram-reverseproxy hiepdangbackup/udagram-reverse-proxy:v4a
  - docker tag udagram-api-feed hiepdangbackup/udagram-api-feed:v4a
  - docker tag udagram-api-user hiepdangbackup/udagram-api-user:v4a
  - docker tag udagram-frontend hiepdangbackup/udagram-frontend:local

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push hiepdangbackup/udagram-api-feed:v4a
  - docker push hiepdangbackup/udagram-api-user:v4a
  - docker push hiepdangbackup/udagram-frontend:local
  - docker push hiepdangbackup/reverseproxy:v4a
